### ISSUE TITLE
Milestone - February (二月) - 2022

### ISSUE THREAD

**Issue by Bistard** [Bistard/MarkdownNote#68]
### Common Codes
* [ ] New emitters
* [ ] ...

### User interface
* [x] Scrollable
* [ ] ...

### Workbench
* [x] KeyboardService - basic functionality
* [x] ShortcutService - basic functionality
* [ ] IpcService - basic functionality

### Unit Tests
* [x] shortcutService related unit tests.
* [ ] Emitters
